version: "3.9"

services:
  api:
    container_name: sdg-forum-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    network_mode: host
    environment:
      HOST: 0.0.0.0
      PORT: 4005
    restart: unless-stopped
