version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4005:3000"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
